### PR TITLE
Update homebrew

### PR DESCRIPTION
**Pull request by EpLiar**
image

I noticed this domain in my daily use of Homebrew and made sure to commit after I encountered it multiple times.

### CODE REVIEW

**Comment by Robot-DaneelOlivaw** [comment]
I've dug in a bit and this CDN seems to be related to [JFrog Bintray](https://bintray.com/), as it's frequently used by Maven, Gradle, Homebrew and more, with the domains `jcenter.bintray.com` or `homebrew.bintray.com`. Bintray probably provides software distribution service for them.

So you might need to add it into `jfrog`. Anyway, nice catch.

**Comment by IceCodeNew** [comment]
> Bintray probably provides software distribution service for them.`jcenter.bintray.com``homebrew.bintray.com`
> 
> So you might need to add it into

Agreed,

**Comment by EpLiar** [comment]
Oh, I see.

But if I add `full:homebrew.bintray.com` into `homebrew`, it will redirect to CloudFront when visit.

So it looks like this PR intends to do something that needs to be changed?

**Comment by Robot-DaneelOlivaw** [comment]
`full:homebrew.bintray.com` in `homebrew` and `full:d29vzk4ow07wi7.cloudfront.net` in `jfrog` will do.

**Pull request merged**
