### PR TITLE
Add shanbay.com leangoo.com

### PR DESCRIPTION
**Pull request by nobody-65534**

### CODE REVIEW

**Comment by IceCodeNew** [comment]
单独的域名可以不用新建一个文件，直接写在 geolocation-cn 下。

**Review by IceCodeNew — CHANGES_REQUESTED** [review]
如上。

**Comment by nobody-65534** [comment]
Thank you for the feedback. I will modify this PR accordingly. 

> 单独的域名可以不用新建一个文件，直接写在 geolocation-cn 下。

There are many entry files under `/data` with only one domain, while `geolocation-cn` has a blob of uncategorized domain list. After following the discussion in #28 , I am still unclear of how the new record should be added, especially for the site with single domain. 

> 如上。
> 另外其实扇贝分类在工具书下也不是特别合适

Any suggestions?

**Comment by IceCodeNew** [comment]
> > 单独的域名可以不用新建一个文件，直接写在 geolocation-cn 下。
> 
> There are many entry files under `/data` with only one domain, while `geolocation-cn` has a blob of uncategorized domain list. After following the discussion in #28 , I am still unclear of how the new record should be added, especially for the site with single domain.

https://github.com/v2fly/domain-list-community/pull/259#issue-511319674
https://github.com/v2fly/domain-list-community/issues/256#issuecomment-719871559

**Review by IceCodeNew — APPROVED** [review]

**Pull request merged**
