### PR TITLE
Update `geolocation-cn`

### PR DESCRIPTION
**Pull request by IceCodeNew**

### CODE REVIEW

**Comment by EpLiar** [comment]
1. `boc` shouldn't be in `abchina`.
2. The IP address of `tuna.moe` is not in China and there is no ICP record at the bottom of the page. This one needs to be discussed.
3. Same to `mokeedev`. It uses CloudFlare's CDN.

**Comment by IceCodeNew** [comment]
> 1. `boc` shouldn't be in `abchina`.

不明白你想表达什么意思，中国银行相关的域名我都是直接从原来的 geolocation-cn 移动过去的，我 dig 了一遍没看出哪里有问题



> * The IP address of `tuna.moe` is not in China and there is no ICP record at the bottom of the page. This one needs to be discussed.
> * Same to `mokeedev`. It uses CloudFlare's CDN.

Fixed.

**Comment by EpLiar** [comment]
> 不明白你想表达什么意思，中国银行相关的域名我都是直接从原来的 geolocation-cn 移动过去的，我 dig 了一遍没看出哪里有问题

abchina 全称是中国农业银行，boc 是中国银行。既然原来的有问题在你搬运的时候就顺手修一下吧。

**Comment by IceCodeNew** [comment]
> > 不明白你想表达什么意思，中国银行相关的域名我都是直接从原来的 geolocation-cn 移动过去的，我 dig 了一遍没看出哪里有问题
> 
> abchina 全称是中国农业银行，boc 是中国银行。既然原来的有问题在你搬运的时候就顺手修一下吧。

噗嗤，懂了。我都没发现这个问题（

**Comment by Loyalsoldier** [comment]
Please rebase branch.

**Comment by IceCodeNew** [comment]
> Please rebase branch.

Done.

**Comment by Loyalsoldier** [comment]
@IceCodeNew 

Please keep adding domains and updating the categories you create in this PR since it's a bit abuse of `category` here. I think a category should be "big" and "rich", or don't create it.

**Comment by IceCodeNew** [comment]
> @IceCodeNew
> 
> Please keep adding domains and updating the categories you create in this PR since it's a bit abuse of `category` here. I think a category should be "big" and "rich", or don't create it.

你说的有道理，很多新创建的分类我也就是起个头，之后应该要继续把 `geolocation-cn` 里没有得到分类的域名搬进去。
顺便关于未来 `geolocation-cn` 里历史数据和新数据的发展方向，我也有些想法，不知道你是否可以来 Issue #28 讨论。
@Loyalsoldier

**Comment by Robot-DaneelOlivaw** [comment]
`geolocation-cn` should keep same structure as `geolocation-!cn` using comment. I don't think there's necessity to create these lists.

**Pull request merged**
