### PR TITLE
Revert category-porn

### LINKED ISSUE #1657: TODO: revert #863
There was a discussion about it, and we are planning to revert the PR #863  
This issue is for notification and tracking the progress.  
  
For anyone who may concern about the discussion, please refer to the following:  
* https://github.com/v2fly/domain-list-community/pull/1655#issuecomment-1543214093

### PR DESCRIPTION
**Pull request by rootmelo92118**
Fix #1657

### CODE REVIEW

**Comment by IceCodeNew** [comment]
How can I verify this PR really fixed #1657?

**Comment by rootmelo92118** [comment]
> How can I verify this PR really fixed #1657?

I can tell you how I operate it. Wait a minute....

**Comment by rootmelo92118** [comment]
First, Use `git blame category-porn | grep "Ryze" >> ../Ryze_submited_domain.txt`. And you will get the file looks like this.
截圖 2023-06-09 上午10 02 15

Second, Use the regular expression to match and remove the data which is unnecessary in every single line. Just leave the domain name. And then it will look like this.
截圖 2023-06-09 上午10 06 58

Third, Write a script and input the domain list and `category-porn`. Remove them from `category-porn`.
```
Ryze_domain_list = []

# Input domain list
while True:
	inputData = input()
	if inputData == "exit":
		break
	else:
		Ryze_domain_list.append(inputData)

# Read category-porn
with open("category-porn","r") as f:
	category_porn = f.readlines()
	f.close()

# Remove "\n" in every single line.
for i in range(0,len(category_porn)):
	category_porn[i] = category_porn[i].strip()

# Remove the domain from Ryze_domain_list
for i in Ryze_domain_list:
	category_porn.remove(i)

# Initalize export data
cleaned_category_porn = ""

# Generate export data
for i in category_porn:
	cleaned_category_porn = cleaned_category_porn + i + "\n"

# Save the result
with open("cleaned-category-porn.txt","a") as f:
	f.write(cleaned_category_porn)
	f.close()
```

**Comment by rootmelo92118** [comment]
@IceCodeNew Did you see that?

**Comment by IceCodeNew** [comment]
> @IceCodeNew Did you see that?

Yep, just give me more time.

**Comment by rootmelo92118** [comment]
It has no mistake of method to remove the domain which are submitted in #863. This PR will be merged. Welcome to discuss if you have any opinion.

**Pull request merged**
