### PR TITLE
Adding "globo" from globo.com 

### PR DESCRIPTION
**Pull request by AndreRibas1**
Adding "globo" from news site globo.com

### CODE REVIEW

**Review by rootmelo92118 — CHANGES_REQUESTED** [review]
Please include this category to relevant category.

**Comment by AndreRibas1** [comment]
Hello, sorry I didn't understand. Could you explain? Do I have to add to a specific category?

**Comment by Lablace** [comment]
> Hello, sorry I didn't understand. Could you explain? Do I have to add to a specific category?

It seems you could add it to `category-media` and/or `category-entertainment`. I think it's some media site like Bloomberg and BBC but I can't read Portuguese. Feel free to correct me if I'm wrong.

**Comment by AndreRibas1** [comment]
Oh yes. It's a media network (news and information)! I will add the categories informed and update the commit

**Comment by Lablace** [comment]
> Oh yes. It's a media network (news and information)! I will add the categories informed and update the commit.
> 
> By the way, should I add both categories? Because it is a news site, but it also has entertainment services (in this case globoplay)

Now I think you could split them into two groups, all entertainment-related go into `globoplay`, others go into `globo`, then add `globoplay` into `category-entertainment`, next include `globoplay` in `globo` and finally add `globo` into `category-media`.

In this case, one can use `globoplay` if he or she wants precedence for entertainment sites over the whole backed by `globo`.

**Comment by rootmelo92118** [comment]
Convert it to ready to review when you finish the process. Then, I will see it.

**Pull request closed without merging**
