### PR TITLE
Fix: trim attribute prefix "@" character

### PR DESCRIPTION
**Pull request by Loyalsoldier**
This commit fixes the `@attr` function.

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Have tested on my local V2Ray and it works.

**Comment by EpLiar** [comment]
Can you provide test data? I use `geosite:baidu-ads@ads` but core can't start.

image

**Comment by Loyalsoldier** [comment]
@EpLiar 
Try to use `geosite.dat` in here: https://github.com/Loyalsoldier/domain-list-community/releases/tag/20200727014528

**Comment by EpLiar** [comment]
My config:

```json
{
  "domain": [
    "geosite:baidu-ads@ads"
  ],
  "outboundTag": "blocked",
  "type": "field"
}
```

image

Even `geosite:baidu-ads`

image

Maybe there's something wrong?

**Comment by EpLiar** [comment]
I use manual compile and your GitHub Action.

**Comment by EpLiar** [comment]
Passed. I change `IPIfNonMatch` to `AsIs`

**Comment by Loyalsoldier** [comment]
I think you should quit the program, clear DNS cache, and then reopen it.

**Comment by EpLiar** [comment]
In my environment, if `geosite:cn` exists, `geosite:baidu-ads@ads` won't work.

image

```json
{
    "dns": {
        "servers": [
            "8.8.8.8",
            "8.8.4.4",
            "223.5.5.5",
            "114.114.114.114",
            "localhost"
        ]
    },
    "inbounds": [
        {
            "port": "1080",
            "protocol": "http",
            "settings": {
            },
            "tag": "http"
        },
        {
            "port": "1081",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true
            },
            "tag": "socks"
        }
    ],
    "log": {
        "loglevel": "warning"
    },
    "outbounds": [
        {
            "protocol": "freedom",
            "settings": {
            },
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "settings": {
            },
            "tag": "blocked"
        }
    ],
    "policy": {
    },
    "reverse": {
    },
    "routing": {
        "settings": {
            "domainStrategy": "IPIfNonMatch",
            "rules": [
                {
                    "domain": null,
                    "ip": [
                        "geoip:cn",
                        "geoip:private"
                    ],
                    "outboundTag": "direct",
                    "port": null,
                    "type": "field"
                },
                {
                    "domain": [
                        "geosite:cn",
                        "geosite:nike",
                        "geosite:apple"
                    ],
                    "outboundTag": "direct",
                    "type": "field"
                },
                {
                    "domain": [
                        "geosite:baidu-ads@ads"
                    ],
                    "outboundTag": "blocked",
                    "type": "field"
                }
            ]
        },
        "strategy": "rules"
    },
    "stats": {
    },
    "transport": {
    }
}

```

**Comment by DuckSoft** [comment]
block rules should be in front of direct & proxy rules.

**Comment by EpLiar** [comment]
> block rules should be in front of direct & proxy rules.

Okay.

**Comment by Robot-DaneelOlivaw** [comment]
Super! Now we can use attribute as we want.

**Pull request merged**
