### PR TITLE
Add Myanmar Bank Domain list category-bank-mm

### PR DESCRIPTION
**Pull request by petermyo**
I would like to contribute myanmar bank domain list since v2fly does not have that list before.

### CODE REVIEW

**Comment by petermyo** [comment]
Let me follow up that data listing on v2fly database.

**Review by rootmelo92118 — CHANGES_REQUESTED** [review]
Do not add the prefix `domain:`. Olease remove it.

And please include this category to relevant category.

**Comment by petermyo** [comment]
> Do not add the prefix `domain:`. Olease remove it.
> 
> And please include this category to relevant category.

I have been updated @rootmelo92118 
I already search Myanmar bank list before and I think this would be new one and I will contribute all Myanmar related list in future. 
Thanks for your response.

**Comment by petermyo** [comment]
It request is still in progress and let me know if need more clarification. @rootmelo92118

**Review by rootmelo92118 — APPROVED** [review]

**Pull request merged**
