### PR TITLE
Update category-porn

### PR DESCRIPTION
**Pull request by rootmelo92118**
remove some repeated ,invalid and not belong to here domain.

### CODE REVIEW

**Comment by rootmelo92118** [comment]
I was remove all domain which is not related to this category, but I still cannot find all invalid domain. Sorry.

**Comment by IceCodeNew** [comment]
> I was remove all domain which is not related to this category, but I still cannot find all invalid domain. Sorry.

Is this PR ready for review?

**Comment by rootmelo92118** [comment]
> Is this PR ready for review?

Yes

**Review by IceCodeNew — APPROVED** [review]

**Comment by IceCodeNew** [comment]
Thanks for your contribution!

**Pull request merged**
