### PR TITLE
add China Express

### PR DESCRIPTION
**Pull request by HankAviator**

### CODE REVIEW

**Comment by EpLiar** [comment]
Where is the `chinaexpressair`?

**Comment by HankAviator** [comment]
> Where is the `chinaexpressair`?

The URL? www.chinaexpressair.com

**Comment by EpLiar** [comment]
You include a non-exist file so it will fail when the program generates `dlc.dat`.

If you want to add this domain, you should create a file named `chinaexpressair` and write `chinaexpressair.com` into it.

Finally, include `chinaexpressair` into `geolocation-cn`.

**Comment by HankAviator** [comment]
Thank you, fixed.

**Review by EpLiar — APPROVED** [review]

**Comment by EpLiar** [comment]
Thank you for your contribution. :-)

**Pull request merged**
