### PR TITLE
fix #1395

### LINKED ISSUE #1395: IPv6地址作为SNI时会匹配private规则的可能性
当IPv6地址作为SNI时，会匹配
https://github.com/v2fly/domain-list-community/blob/7d24ecd45c7aecc3e23bfc4dce5964dfdc505858/data/private#L121-L122
`private`的这条规则。

巧合的是，IPv4地址作为SNI时并不会出现问题。其原因是IPv4地址本身包含`.`，恰好会被排除掉。

是否可以考虑把此规则替换成`regexp:^[^.:]+$`?

### PR DESCRIPTION
**Pull request by IceCodeNew**

### CODE REVIEW

**Comment by IceCodeNew** [comment]
https://github.com/v2fly/domain-list-community/blob/c202f7fca603f68cb7e3aeb4476d4511dcd5ddfa/main.go#L120

This project has a bug that will block this PR from merging.
Do not know whether the v2fly/v2ray-core project is affected by a similar bug.

**Comment by kabegoe** [comment]
How about `^[-0-9A-Za-z]+$`?

**Comment by IceCodeNew** [comment]
> How about `regexp:^[-0-9A-Za-z]+$`?

I was thinking the same thing. Give me some time to ensure exactly what characters could be there in all kinds of valid domains.

**Review by rootmelo92118 — APPROVED** [review]
Ok, I respect your opinion.

**Comment by IceCodeNew** [comment]
credit to @mazzz1y
Thanks for sharing the RFC specification. Or this PR may never be done as I have been too lazy to do some research on it.

**Pull request merged**
