### PR TITLE
Update bytedance-ads

### PR DESCRIPTION
**Pull request by Janet-Baker**
`https://www.pangle.cn/support/doc/5dd0fe756b181e00112e3ec5`
From official documents.

### CODE REVIEW

**Comment by IceCodeNew** [comment]
> Maybe we can set it like this:
> 
> ```
> # Document at https://www.pangle.cn/support/doc/5dd0fe618507820012088272#7a17be
> snssdk.com @ads
> pstatp.com @ads
> dig.bdurl.net @ads
> 
> # Document at https://www.pangle.cn/support/doc/5fcc8ef7253fee000ed14efa#%E6%96%B9%E5%BC%8F%E4%BA%8C
> artifact.bytedance.com
> 
> # Documents in old versions
> byted.org
> ctobsnssdk.com
> pglstatp-toutiao.com
> pangolin-sdk-toutiao.com
> ```

This format looks good to me. But why are you compressing `*.snssdk.com` domains to `snssdk.com`?
I could not find any clues for this top domain is ONLY for advertising purposes.

**Comment by Janet-Baker** [comment]
expand:
```
i.snssdk.com @ads
is.snssdk.com @ads
pangolin.snssdk.com @ads
extlog.snssdk.com @ads
bds.snssdk.com @ads
```

A request to `snssdk.com` will be redirect to `app.toutiao.com`.
But we found other domain exist:
https://github.com/v2fly/domain-list-community/blob/e53d0b7c1e38a22a93d654d8636a4d5cd2951726/data/bytedance-ads#L1
So it's not so strange to compress `*.snssdk.com` domains to `snssdk.com`

**Comment by IceCodeNew** [comment]
> So it's not so strange to compress `*.snssdk.com` domains to `snssdk.com`

I can't see the logic here. There might be a domain `api.snssdk.com` which serves the normal request.

**Comment by IceCodeNew** [comment]
I am ok with it.
How about you? @KevinZonda

**Comment by IceCodeNew** [comment]
BTW there are few domains that have no `@ads` attr. May I ask why?

**Comment by Janet-Baker** [comment]
Modified.
` @ads` is now applied.

**Comment by IceCodeNew** [comment]
Well, at least, we can revert this commit.

**Comment by KevinZonda** [comment]
> Maybe we can set it like this:
> 
> ```
> # Document at https://www.pangle.cn/support/doc/5dd0fe618507820012088272#7a17be
> dig.bdurl.net @ads
> 
> ## pstatp.com
> sf3-ttcdn-tos.pstatp.com @ads
> 
> ## snssdk.com
> bds.snssdk.com @ads
> extlog.snssdk.com @ads
> i.snssdk.com @ads
> is.snssdk.com @ads
> pangolin.snssdk.com @ads
> 
> # Documents in old versions
> ctobsnssdk.com @ads
> pangolin-sdk-toutiao.com @ads
> pglstatp-toutiao.com @ads
> ```

@IceCodeNew No idea, prefer this style than current one :O

**Pull request merged**
