### PR TITLE
Add Chaoxing educational websites

### PR DESCRIPTION
**Pull request by wangshengxin1998**
数据来自
https://beian.tianyancha.com/i863e132996538
超星是中国教育界比较知名的网站，大多数高等院校都购买他们的数据库，以供师生在校访问

### CODE REVIEW

**Comment by IceCodeNew** [comment]
1. sort this list
2. include this list in the `category-scholar-cn` list
3. revert the commit https://github.com/v2fly/domain-list-community/commit/cbcd428a1a3a5e85fd7f557e234aeedf10c83dbf

**Comment by yurenzhen** [comment]
@wangshengxin1998 
1. 让你把你的域名列表按字母排好序.
2. 把你新加的文件名添加到data/category-scholar-cn文件中, 类似如下(注意按照字母排序添加到合适的位置):
include:chaoxing

**Comment by rootmelo92118** [comment]
> * sort this list
> * include this list in the `category-scholar-cn` list
> * revert the commit [cbcd428](https://github.com/v2fly/domain-list-community/commit/cbcd428a1a3a5e85fd7f557e234aeedf10c83dbf)

Can I create a new pull requests to help he(she) to do this operation?
Or I just ignore this pull request to make he(she) to do this operation by himself(herself)?

**Comment by IceCodeNew** [comment]
> Can I create a new pull requests to help he(she) to do this operation

Feel free to do so. Just make sure you had given the credit to the original author by mentioning them in the commit message.

**Pull request closed without merging**
