### PR TITLE
Create pgyer

### PR DESCRIPTION
**Pull request by Vixb1122**

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
I suggest you also add the domains of these products to the file, then sort it. And add this line `include: pgyer` in `geolocation-cn` list.

image

**Comment by Loyalsoldier** [comment]
Please add this line `include:pgyer` in `geolocation-cn` list by alphabetical order.

**Comment by Vixb1122** [comment]
over

**Review by Loyalsoldier — APPROVED** [review]
Thanks for your work 🎉

**Pull request merged**
