### PR TITLE
Add xiaomiflash.com

### PR DESCRIPTION
**Pull request by nobody-65534**

### CODE REVIEW

**Review by KevinZonda — APPROVED** [review]

**Comment by zhullyb** [comment]
I think this is a UnOfficial website, right ?

**Comment by KevinZonda** [comment]
> I think this is a UnOfficial website, right ?

Cool find.

Refer: <https://www.reddit.com/r/Xiaomi/comments/cdx049/is_this_the_official_link_for_the_miflash_tool/>

**Comment by KevinZonda** [comment]
How to solve such problem? Add a comment or?
/cc @EpLiar

**Comment by Loyalsoldier** [comment]
> How to solve such problem? Add a comment or?
> /cc @EpLiar

Remove `xiaomiflash.com` from `xiaomi` and add it to `geolocation-cn`

**Comment by KevinZonda** [comment]
Cool, I'll do it later. Cheers!

26 Mar 2021, 04:41 by ***@***.***:

**Comment by Loyalsoldier** [comment]
> Cool, I'll do it later. Cheers! 26 Mar 2021, 04:41 by ***@***.***:

Done in #484

**Comment by KevinZonda** [comment]
Cheers :)

29 Mar 2021, 09:03 by ***@***.***:

**Pull request merged**
