### PR TITLE
Add Iranian domains that qualify for reduced internet usage rates from Iranian ISPs

### PR DESCRIPTION
**Pull request by IRConf**
The websites listed on https://eservices.ito.gov.ir/page/iplist are eligible for discounted internet usage rates for Iranian users who access them with Iranian IP addresses. To ensure faster access and take advantage of the discount, it is recommended to establish direct connections.

[This repository](https://github.com/IRConf/Iranian-Half-Price-Traffic-Websites-List.git) provides a script that can automatically gather this website list and extract their domains every day. The domain list can be accessed [here](https://raw.githubusercontent.com/IRConf/Iranian-Half-Price-Traffic-Websites-List/main/domains), which can be used as the source for the category-ir-half-price file.

### CODE REVIEW

**Comment by rootmelo92118** [comment]
Please provide the source.

**Comment by IceCodeNew** [comment]
Thanks for showing interest in contributing to this project. There is a great gap in "barely works for the Iranians". And any help would be appreciated.
However, we can not accept this pull request yet, as it is simply too large for anyone to review it. (It does not matter whether the quality of your script is good enough, nor whether your idea makes sense.)
Would you consider forking this project and maintaining it separately? There used to be a similar discussion at https://github.com/v2fly/domain-list-community/pull/1376#issuecomment-1439344349

**Comment by IRConf** [comment]
@IceCodeNew Thank you for considering my pull request and for the feedback. I understand the review process can be overwhelming, and I appreciate your suggestion to maintain a separate fork. However, I am still interested in helping with the review process. Please provide some guidance on the criteria used to evaluate pull requests and any specific steps involved in the review process. This information would help me understand how best to contribute and ensure that my contributions align with the project's goals and standards. Thank you for your time, and I look forward to hearing back from you.

**Comment by rootmelo92118** [comment]
> @IceCodeNew Thank you for considering my pull request and for the feedback. I understand the review process can be overwhelming, and I appreciate your suggestion to maintain a separate fork. However, I am still interested in helping with the review process. Please provide some guidance on the criteria used to evaluate pull requests and any specific steps involved in the review process. This information would help me understand how best to contribute and ensure that my contributions align with the project's goals and standards. Thank you for your time, and I look forward to hearing back from you.

I don't recommend citing it directly to this warehouse, which will cause difficulties in review and cannot update the domain name in real-time. Instead, I recommend integrating it into https://github.com/Loyalsoldier/v2ray-rules-dat and adding it to third-party geosite.dat with daily updates.

If you can accept my proposal, you can contact @Loyalsoldier.

**Comment by rootmelo92118** [comment]
@IRConf I make a fork to maintain it. I wrote it in the makedown in English. This pull request will be closed directly.
https://github.com/rootmelo92118/v2ray-rules-dat

**Pull request closed without merging**
