### PR TITLE
Multiple websites are added

### PR DESCRIPTION
**Pull request by molink36**

### CODE REVIEW

**Comment by IceCodeNew** [comment]
> > I assume that this pr is good to go. Have you finished reviewing this pr? @KevinZonda
> 
> Still under CRing

What is CRing?

**Comment by KevinZonda** [comment]
> > > I assume that this pr is good to go. Have you finished reviewing this pr? @KevinZonda
> > 
> > Still under CRing
> 
> What is CRing?

C(ode) R(review) ing

**Comment by IceCodeNew** [comment]
Ping
@KevinZonda

**Comment by IceCodeNew** [comment]
> @IceCodeNew I think currectly it is alright, but still not perfect. I will be apprectated that if you could help me review it again. Thanks.

Got it

**Pull request merged**
