### PR TITLE
Update geolocation-cn

### PR DESCRIPTION
**Pull request by Vixb1122**

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
There is No access point for `snipaste.com` in China mainland. It's inappropriate to add it to `geolocation-cn` list.

**Comment by Vixb1122** [comment]
`zh.snipaste.com` instead

**Comment by Loyalsoldier** [comment]
> `zh.snipaste.com` instead

No access point in China mainland either:

image

**Comment by Vixb1122** [comment]
all right！

**Pull request closed without merging**
