### PR TITLE
Create roku

### PR DESCRIPTION
**Pull request by tritu**
Roku streaming players, Roku TV and the Roku Channel

### CODE REVIEW

**Comment by EpLiar** [comment]
1. Please sort the domains.
2. Include `roku` into `category-media`
3. Make the commit log clean.

**Comment by EpLiar** [comment]
I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?

**Comment by EpLiar** [comment]
一会完事之后需要 rebase 一下分支

**Comment by tritu** [comment]
> I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?

fandango and mgo are Roku's movie store and hardcoded in Roku TV.

**Comment by EpLiar** [comment]
> > I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?
> 
> fandango and mgo are Roku's movie store and hardcoded in Roku TV.

好的，那么 rebase 一下吧，或者 reset 重头来也行 (中间多了一个不必要的 commit)。添加到 category-media 的那个commit 信息可能不太合适，稍微改改会更好。

**Comment by tritu** [comment]
> > > I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?
> > 
> > 
> > fandango and mgo are Roku's movie store and hardcoded in Roku TV.
> 
> 好的，那么 rebase 一下吧，或者 reset 重头来也行 (中间多了一个不必要的 commit)。添加到 category-media 的那个commit 信息可能不太合适，稍微改改会更好。



> > > I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?
> > 
> > 
> > fandango and mgo are Roku's movie store and hardcoded in Roku TV.
> 
> 好的，那么 rebase 一下吧，或者 reset 重头来也行 (中间多了一个不必要的 commit)。添加到 category-media 的那个commit 信息可能不太合适，稍微改改会更好。



> > > I checked the wiki and couldn't find anything related to Fandango and Roku. Can you provide a source?
> > 
> > 
> > fandango and mgo are Roku's movie store and hardcoded in Roku TV.
> 
> 好的，那么 rebase 一下吧，或者 reset 重头来也行 (中间多了一个不必要的 commit)。添加到 category-media 的那个commit 信息可能不太合适，稍微改改会更好。

Roku is more like Netflix, Disney and Sling. That's why it's better to be under "entertainment" not "media". Try to rebase now.

**Comment by EpLiar** [comment]
> Roku is more like Netflix, Disney and Sling. That's why it's better to be under "entertainment" not "media". Try to rebase now.

OK 的。如果不会 rebase 的话可以 reset --fost 到最初再 commit 两次，不着急。

**Pull request closed without merging**
