### PR TITLE
Update category-porn

### PR DESCRIPTION
**Pull request by Loyalsoldier**
https://github.com/Loyalsoldier/v2ray-rules-dat/issues/290

### CODE REVIEW

**Review by IceCodeNew — APPROVED** [review]

**Comment by IceCodeNew** [comment]
fix #863

**Comment by IceCodeNew** [comment]
That was a fault of my early maintenance work. I basically will not give approval should a PR based on any third-party list now.
Since #863 already caused problems, I would like to revert it. What do you think? @rootmelo92118 @RyzeChang @Loyalsoldier

**Comment by RyzeChang** [comment]
I’m very sorry for not thoroughly checking list and causing this issue. I completely agree with your perspective and revert this Pull Request is the right decision.

**Comment by rootmelo92118** [comment]
> That was a fault of my early maintenance work. Since then, for the most of the time, I do not approve a pull request if it is based on any third-party list.
> Since #863 already caused problems, I would like to revert it. What do you think? @rootmelo92118 @RyzeChang @Loyalsoldier

Actually, we don't have choice because I got this notification when I tried to revert it.
`Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. `

**Comment by RyzeChang** [comment]
> > That was a fault of my early maintenance work. Since then, for the most of the time, I do not approve a pull request if it is based on any third-party list.
> > Since #863 already caused problems, I would like to revert it. What do you think? @rootmelo92118 @RyzeChang @Loyalsoldier
> 
> Actually, we don't have any choice because I got this notification when I tried to revert it. `Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. ` @RyzeChang By the way, do I need to translate #867 into English? According to your homepage of GitHub, I guess you can understand Chinese but I am not sure.

“No, it’s not necessary to translate #867 into English.

**Comment by IceCodeNew** [comment]
> Actually, we don't have any choice because I got this notification when I tried to revert it. `Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. `

Well, no worries about it. I will handle it ；-）
Reverting that PR is definitely going to have conflicts that require some git skills & time to resolve. That is why you saw those warnings.

**Pull request merged**
