### PR TITLE
Update azure, microsoft and xbox

### PR DESCRIPTION
**Pull request by KukiSa**
## 微软（中国）有限公司 京ICP备09042378号

Active:
`msra.cn` 京ICP备09042378号-2
`engkoo.com` 京ICP备09042378号-3
`mspil.cn` 京ICP备09042378号-4
`o365cn.com` 京ICP备09042378号-26
`o365files.cn` 京ICP备09042378号-27

Not active:
`boswp.com` 京ICP备09042378号-17
`s-msft.com` 京ICP备09042378号-17

Active, but not in Chinese Mainland:
`kumo.com` 京ICP备09042378号-17

`msn.net` is used as rDNS for Microsoft backbone network hops, for example:
`104.44.235.100 Tokyo, Japan. microsoft.com, AS8075`
```
# dig -x 104.44.235.100 +short
ae20-0.icr02.tyo31.ntwk.msn.net.
```

### CODE REVIEW

**Comment by rootmelo92118** [comment]
What's the mean "not active"?

**Comment by KukiSa** [comment]
> What's the mean "not active"?

Unaccessible.

**Comment by rootmelo92118** [comment]
> > What's the mean "not active"?
> 
> Unaccessible.

Do you mean it has subdomains but the primary domain is unreachable?

**Comment by KukiSa** [comment]
> > > What's the mean "not active"?
> > 
> > 
> > Unaccessible.
> 
> Do you mean it has subdomains but the primary domain is unreachable?

I can not confirm. 
All I know is that the domains belong to `microsoft` and they are currently unreachable.
Adding `@cn` is not recommended unless there is solid evidence.

**Review by rootmelo92118 — APPROVED** [review]

**Pull request merged**
