### PR TITLE
Create cygames

### PR DESCRIPTION
**Pull request by jwstaceyOvO**
popular mobile games from cygames

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
I don't like the idea of matching domains by using keywords. Maybe you should use more explicit ones?

**Comment by jwstaceyOvO** [comment]
> I don't like the idea of matching domains by using keywords. Maybe you should use more explicit ones?

Recently, I find that Pretty Derby has changed data link from https://prd-storage-umamusume.akamaized.net/ to https://prd-storage-game-umamusume.akamaized.net/, World Flipper has also added a datalink https://worldflipper.akamaized.net/, which did not exist in previous versions. So, I use keyword to position such links, you don't know when cygames will change them.

**Comment by jwstaceyOvO** [comment]
@Loyalsoldier  Is cygames.co.jp really necessary? I don't find any link of related game api or game data, and such domains don't need special ip to access.

**Comment by Loyalsoldier** [comment]
@jwstaceyOvO  Actually I miss `umamusume.jp`. Added because it belongs to cygames.

**Pull request merged**
