### PR TITLE
Update category-ads

### PR DESCRIPTION
**Pull request by rootmelo92118**

### CODE REVIEW

**Review by KevinZonda — COMMENTED** [review]
Quite not sure about the url's usage. If any evidence shows that this one is a tracker can be provided would be verry appreciate.

**Comment by rootmelo92118** [comment]
> Quite not sure about the url's usage. If any evidence shows that this one is a tracker can be provided would be verry appreciate.
截圖 2022-08-28 上午9 31 23
截圖 2022-08-28 上午9 32 01

I have telegram chat history and twitter's post to prove this domain is a tracker.
<a href="https://twitter.com/germanyorthoped/status/1298110413612015618?lang=ar-x-fm">post</a>

**Comment by KevinZonda** [comment]
Quite not sure its catalogue
@IceCodeNew hi, do u think it belongs to ads or..

**Comment by IceCodeNew** [comment]
> Quite not sure its catalogue @IceCodeNew hi, do u think it belongs to ads or..

Seems we have been mixing the tracker sites with ads sites since the very beginning, so it should be fine.

**Comment by IceCodeNew** [comment]
Reverted. Pls have a look at #1130

**Pull request merged**
