### PR TITLE
illusion-nonofficial: : Delete all .cn domains

### PR DESCRIPTION
**Pull request by mayampi01**

### CODE REVIEW

**Review by rootmelo92118 — APPROVED** [review]

**Review by IceCodeNew — CHANGES_REQUESTED** [review]
Why not just mark them with `@!cn` labels?
We do not delete domains for no apparent reason.

**Comment by IceCodeNew** [comment]
I am open to this PR, but more detail is required.

**Comment by IceCodeNew** [comment]
You are making point here. Though, you are supposed to provide evidences to prove that those three domains are expired (do not confuse with sites been not accessiable. That domain must be expired/deleted)

**Comment by IceCodeNew** [comment]
> These three domains were added to `illusion-nonofficial` in 2022. [f4a11e4](https://github.com/v2fly/domain-list-community/commit/f4a11e41336288e05fc0bb69c86a53c241b9b72e)
> 
> ```
> $ whois clincha.cn
> ...
> Registration Time: 2023-10-14 19:42:57
> ...
> ```
> 
> ```
> $ whois illusionfb.cn
> No matching record.
> ```
> 
> ```
> $ whois yiqilai99.cn
> ...
> Registration Time: 2023-06-07 04:57:57
> ...
> ```
> 
> These domain names are either not recorded or have been re-registered (which means the original ones have expired or been deleted).

terrific, I have re-introduced this change into the master branch. Thanks for your contribution.

**Pull request merged**
