### PR TITLE
Update aws

### PR DESCRIPTION
**Pull request by KukiSa**
宁夏西云数据科技有限公司

`a2z.org.cn` 宁ICP备17000743号-18
`amazonaws.cn` 宁ICP备17000743号-11
`amazonaws.com.cn` 宁ICP备17000743号-11
`amazonwebservices.com.cn` 宁ICP备17000743号-24
`asfiovnxocqpcry.com.cn` 宁ICP备17000743号-19
`aws-border.cn` 宁ICP备17000743号-23
`aws-icp-domain-manager.cn` 宁ICP备17000743号-16
`awsapps.cn` 宁ICP备17000743号-15
`awsapps.com.cn` 宁ICP备17000743号-15
`awsstatic.cn` 宁ICP备17000743号-21
`cloudfront-cn.net` 宁ICP备17000743号-9
`cloudfront-test.cn` 宁ICP备17000743号-17
`cloudfront.cn` 宁ICP备17000743号-10
`nwcdcloud.cn` 宁ICP备17000743号-2
`nwcdcloud.com.cn` 宁ICP备17000743号-2
`nwcddns.cn` 宁ICP备17000743号-3
`nwcdinfosec.cn` 宁ICP备17000743号-22
`route53.cn` 宁ICP备17000743号-4
`sagemaker.com.cn` 宁ICP备17000743号-20

`awsdns-cn-[0-9][a-e0-9]\.cn` 宁ICP备17000743号-5/宁ICP备17000743号-13 (e.g. `awsdns-cn-8b.cn`)
`awsdns-cn-[0-9][0-9]\.biz` 宁ICP备17000743号-8
`awsdns-cn-[0-9][0-9]\.com` 宁ICP备17000743号-6
`awsdns-cn-[0-9][0-9]\.net` 宁ICP备17000743号-7
`awsdns-cn-[0-9][0-9]\.top` 宁ICP备17000743号-14 (e.g. `awsdns-cn-25.top`)

### CODE REVIEW

**Comment by IceCodeNew** [comment]
It would be better to move these sites into a separate list like `aws-cn`
@rootmelo92118 @KukiSa

**Comment by rootmelo92118** [comment]
> It would be better to move these sites into a separate list like `aws-cn` @rootmelo92118 @KukiSa 

It sounds like a good idea. And welcome back.

**Comment by IceCodeNew** [comment]
> > It would be better to move these sites into a separate list like `aws-cn` @rootmelo92118 @KukiSa
> 
> It sounds like a good idea. And welcome back.

;-)

**Comment by KukiSa** [comment]
> It would be better to move these sites into a separate list like `aws-cn` @rootmelo92118 @KukiSa

I agree too. Welcome come back and have a nice day.

**Pull request merged**
