### PR TITLE
Add websites

### PR DESCRIPTION
**Pull request by aitsuki-lan**
Add baijiayun, duitang, doc88, docin, koolearn and nat-test.

### CODE REVIEW

**Comment by IceCodeNew** [comment]
If making a PR is difficult for you. I'm here to help.

**Comment by lanyuue** [comment]
> If making a PR is difficult for you. I'm here to help.

I'm sorry for the mistaken commits, may i fork again and retry?

**Comment by IceCodeNew** [comment]
> > If making a PR is difficult for you. I'm here to help.
> 
> I'm sorry for the mistaken commits, so i  should fork a new one every time before i try to submit a PR.

Nop, use rebase.

git rebase HEAD~<the number of your commits>
Put a "b" at the first line.
Exit the editor.
git reset upstream/master
git rebase --continue

Solve the conflict if there is any.
git push -f

**Comment by lanyuue** [comment]
> 
> 
> > > If making a PR is difficult for you. I'm here to help.
> > 
> > 
> > I'm sorry for the mistaken commits, so i  should fork a new one every time before i try to submit a PR.
> 
> Nop, use rebase.
> 
> git rebase HEAD~ Put a "b" at the first line. Exit the editor. git reset upstream/master git rebase --continue
> 
> Solve the conflict if there is any. git push -f

thanks a lot! I made a new PR, will that be ok now?🥺

**Pull request closed without merging**
