### PR TITLE
Added ITO listed iranian domains

### PR DESCRIPTION
**Pull request by IceCodeNew**
Will fix https://github.com/v2fly/domain-list-community/pull/1340 and close https://github.com/v2fly/domain-list-community/issues/1337.

### CODE REVIEW

**Comment by IceCodeNew** [comment]
I need time to process this PR. Please do not merge this PR before I give my approval.
You are welcome to leave suggestions or other comments ;-)

**Comment by debMan** [comment]
Do you have any suggestion to name this file?
It's not a separate category, because it contains domains of several categories. It could be something like `ir-local` or `ir-regulated`.

**Comment by IceCodeNew** [comment]
Bad news, my computer is broken. Seems I will not be able to process this PR till the next week.

**Comment by debMan** [comment]
Hi. Any update on this?

**Comment by rootmelo92118** [comment]
> Hi. Any update on this?

I think is not.

**Comment by rootmelo92118** [comment]
What is the difference between https://github.com/v2fly/domain-list-community/pull/1346 to https://github.com/v2fly/domain-list-community/pull/1375? If you are the same, we only can merge one.

**Comment by bootmortis** [comment]
Just like to mention these two comments here:

https://github.com/v2fly/domain-list-community/pull/1438#issuecomment-1428404334

https://github.com/v2fly/domain-list-community/pull/1438#issuecomment-1428484966


If this or #1375 merged, people are going to have issues.

**Comment by rootmelo92118** [comment]
According to our consensus, this pull request will be closed.

**Pull request closed without merging**
