### PR TITLE
Added huangyuhui.net to geolocation-cn

### PR DESCRIPTION
**Pull request by Nep-Timeline**

### CODE REVIEW

**Comment by IceCodeNew** [comment]
I think it would be better to put that domain under a category named `category-blog-cn`, then you can include it in this `geolocation-cn` category.

**Review by IceCodeNew — CHANGES_REQUESTED** [review]
I think it would be better to put that domain under a category named `category-blog-cn`, then you can include it in this `geolocation-cn` category.

**Comment by Nep-Timeline** [comment]
> I think it would be better to put that domain under a category named `category-blog-cn`, then you can include it in this `geolocation-cn` category.

#1659 like this?

**Comment by IceCodeNew** [comment]
suppressed by #1659

**Pull request closed without merging**
