### PR TITLE
Update private

### PR DESCRIPTION
**Pull request by database64128**

### CODE REVIEW

**Review by EpLiar — APPROVED** [review]

**Comment by Loyalsoldier** [comment]
`include:filename@attr` doesn't work.

**Comment by Loyalsoldier** [comment]
I think we should rewrite the build process and find a better way in several days. So draft it for now.

**Comment by kslr** [comment]
What would you do

**Comment by Loyalsoldier** [comment]
> What would you do

I'll rewrite the build process and add some features.

**Comment by database64128** [comment]
I think we should merge the PR first. We can make changes after the new build process is deployed.

**Comment by Loyalsoldier** [comment]
I think we should move all `@private` domains to the `private` file.

**Comment by database64128** [comment]
> I think we should move all `@private` domains to the `private` file.

Agreed. But you forgot to add `openwrt.lan` to `private` in 16abfd4. 😅

**Comment by Loyalsoldier** [comment]
> Agreed. But you forgot to add `openwrt.lan` to `private` in [16abfd4](https://github.com/v2fly/domain-list-community/commit/16abfd4399b25f665f051ac337dfe9edec8e5fe4). 😅

`lan` TLD is already in `private` file.

**Pull request merged**
