### PR TITLE
google: sync @cn rules with upstream

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Review by database64128 — APPROVED** [review]
LGTM. Since the commit was signed with your GPG key, I'm going to leave it for you to merge it.

**Comment by IceCodeNew** [comment]
感觉有必要做一个自动同步的服务了

**Comment by KukiSa** [comment]
```
full:crl.pki.goog @cn
full:ocsp.pki.goog @cn
full:pki-goog.l.google.com @cn
```
已经或应当在 `google-trust-services` 中列出，下次应该过滤此 3 行。

**Comment by IceCodeNew** [comment]
> ```
> full:crl.pki.goog @cn
> full:ocsp.pki.goog @cn
> full:pki-goog.l.google.com @cn
> ```
> 
> 已经或应当在 `google-trust-services` 中列出，下次应该过滤此 3 行。

Good catch

**Pull request merged**
