### PR TITLE
feat: add category-container and include into category-dev

### PR DESCRIPTION
**Pull request by kunish**
As the title suggests, this PR adds category-container, which includes most of the container registry domain.

This file is also included in category-dev

### CODE REVIEW

**Comment by kunish** [comment]
Not quite sure about the regexp syntax, any suggestions?

**Comment by rootmelo92118** [comment]
> Not quite sure about the regexp syntax, any suggestions?

I think your regular expression is wrong. Please tell me what are you want to do. Maybe I can help you to write a correct expression.

**Comment by kunish** [comment]
Here's the link of [Amazon ECR private registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html)

**Comment by kunish** [comment]
And here's the link of [Amazon container image registries](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html)

**Review by IceCodeNew — APPROVED** [review]

**Review by rootmelo92118 — APPROVED** [review]
It looks good.

**Pull request merged**
