### PR TITLE
patch(geolocation-cn): add zhihu

### PR DESCRIPTION
**Pull request by yqlbu**
## Summary

As the title suggests.

### CODE REVIEW

**Comment by nb5p** [comment]
Why bilibili2? This is a pornographic website.

**Comment by yqlbu** [comment]
> Why bilibili2? This is a pornographic website.

Ohh really? I’m not aware of this.. let me remove it from the list then.

**Comment by yqlbu** [comment]
> Why bilibili2? This is a pornographic website.

Resolved. Removed it from the list.

**Review by rootmelo92118 — CHANGES_REQUESTED** [review]
`bilibili-game` has already included in `bilibili`. You don't need to include it again.

**Comment by yqlbu** [comment]
> `bilibili-game` has already included in `bilibili`. You don't need to include it again.

Sure, thanks for the kind notes. Resolved.

**Comment by nb5p** [comment]
Zhihu is the same that is included in the item called category-social-media-cn. If you visit Zhihu and it is not included in geolocation-cn, it may be a software bug.

**Comment by yqlbu** [comment]
> Zhihu is the same that is included in the item called category-social-media-cn. If you visit Zhihu and it is not included in geolocation-cn, it may be a software bug.

Ok. Understood. I will close this issue then.

**Pull request closed without merging**
