### PR TITLE
Update microsoft

### PR DESCRIPTION
**Pull request by EpLiar**

### CODE REVIEW

**Comment by EpLiar** [comment]
Conflict resolved.

**Comment by Loyalsoldier** [comment]
1. Please rebase branch, not fast-forward
2. typo `include: microstf-dev` in `microsoft`

**Comment by Loyalsoldier** [comment]
And please add these domains:

```
vsassets.io
visualstudio.com
```

For vscode plugin install.

**Comment by EpLiar** [comment]
@Loyalsoldier All things done.

**Pull request merged**
