### PR TITLE
Add blurams and AnyDesk and update Iran domains

### PR DESCRIPTION
**Pull request by fakhamatia**

### CODE REVIEW

**Comment by rootmelo92118** [comment]
Please include `anydesk` and `blurams` in the category they should belong to.

**Comment by fakhamatia** [comment]
> Please include `anydesk` and `blurams` in the category they should belong to.

What is right category for `anydesk` and `rustdesk` and `teamviewer` and `blurams`

**Comment by rootmelo92118** [comment]
Maybe you can create a new category which name is `category-remote-control`.

**Comment by fakhamatia** [comment]
> Maybe you can create a new category which name is `category-remote-control`.

And for `blurams`? [Blurams Officlial Smart Home Security Camera](https://www.blurams.com/)

**Comment by rootmelo92118** [comment]
Built failed, please fix it.

**Review by rootmelo92118 — APPROVED** [review]

**Comment by IceCodeNew** [comment]
Thanks for the contribution!
Just to clarify, there is nothing I would like to request an immediate correction, only want to share some tips for the next PRs. PTAL @fakhamatia @rootmelo92118 

1. A good PR should only have 1 go.
For example, there should be a PR for creating the `data/category-remote-control`, a PR for updating the `data/category-ir`, and another PR for introducing the `blurams`.

2. There is no need to introduce a sub-category if there is only one domain constitutes it.
For example, we do not need the files `data/anydesk`, `data/nomachine`, `data/rustdesk` & `data/teamviewer` here.

**Pull request merged**
