### PR TITLE
Create apkcombo

### PR DESCRIPTION
**Pull request by rootmelo92118**
#830

### CODE REVIEW

**Comment by IceCodeNew** [comment]
I would suggest moving this site to the same category as `apkpure.com`.

**Comment by rootmelo92118** [comment]
> I would suggest moving this site to the same category as `apkpure.com`.

So did you advise me to create a new category to include all apk download stations?

**Comment by IceCodeNew** [comment]
> > I would suggest moving this site to the same category as `apkpure.com`.
> 
> So did you advise me to create a new category to include all apk download stations?

Sounds good to me. If you are willing to do it, then go ahead ;-)

**Comment by rootmelo92118** [comment]
> > > I would suggest moving this site to the same category as `apkpure.com`.
> > 
> > 
> > So did you advise me to create a new category to include all apk download stations?
> 
> Sounds good to me. If you are willing to do it, then go ahead ;-)

Ok, I created it.

**Comment by IceCodeNew** [comment]
How about renaming the newly created file as `category-android-app-download`.

**Comment by IceCodeNew** [comment]
Thanks for your contribution!

**Pull request merged**
